version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 27ecJ3ieP
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: